//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFront
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACRA_R_CurrentOverdue
    {
        public long overd_ID { get; set; }
        public Nullable<int> l_type { get; set; }
        public Nullable<long> fk_result_ID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> currID { get; set; }
    }
}
