//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFront
{
    using System;
    
    public partial class ACRA_LoansGetDetEx_Result1
    {
        public long loan_ID { get; set; }
        public Nullable<int> l_type { get; set; }
        public string CreditID { get; set; }
        public string SourceName { get; set; }
        public Nullable<int> currID { get; set; }
        public string exch_code { get; set; }
        public Nullable<double> ExRate { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> BalanceAMD { get; set; }
        public Nullable<double> PMT { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> AmountAMD { get; set; }
        public Nullable<int> LoanClass { get; set; }
        public string LClass { get; set; }
        public Nullable<System.DateTime> CreditingDate { get; set; }
        public Nullable<double> Interest { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<double> ContractAmount { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> CreditScope { get; set; }
        public string Scope { get; set; }
        public string PledgeSubject { get; set; }
        public string CollateralNotes { get; set; }
        public Nullable<double> CollateralAmount { get; set; }
        public Nullable<int> CollateralCurrency { get; set; }
        public Nullable<int> CreditStatus { get; set; }
        public string CStatus { get; set; }
        public Nullable<int> DelayPaymentQuantity1_12 { get; set; }
        public Nullable<int> DelayPaymentQuantity13_24 { get; set; }
        public Nullable<int> DelayPaymentFrequency1_12 { get; set; }
        public Nullable<int> DelayPaymentFrequency13_24 { get; set; }
        public Nullable<System.DateTime> IncomingDate { get; set; }
        public Nullable<double> AmountOverdue { get; set; }
        public Nullable<System.DateTime> CreditStart { get; set; }
        public Nullable<System.DateTime> OutstandingDate { get; set; }
        public Nullable<double> OutstandingPercent { get; set; }
        public Nullable<double> PaymentAmount { get; set; }
        public Nullable<System.DateTime> ClassificationLastDate { get; set; }
        public string CreditNotes { get; set; }
        public Nullable<int> ProlongationsNum { get; set; }
        public Nullable<int> sumOutstandingDaysCount { get; set; }
        public Nullable<double> GuarantorAmount { get; set; }
        public string CreditUsePlaceText { get; set; }
        public Nullable<int> PersonCount { get; set; }
        public Nullable<int> GuarantorCount { get; set; }
    }
}
