//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFront
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACRA_Interrelated
    {
        public long irId { get; set; }
        public Nullable<long> resultId { get; set; }
        public string iNumber { get; set; }
        public string iCreditStart { get; set; }
        public string iLastInstallment { get; set; }
        public Nullable<double> iContractAmount { get; set; }
        public Nullable<double> iAmountDue { get; set; }
        public Nullable<double> iAmountOverdue { get; set; }
        public Nullable<double> iOutstandingPercent { get; set; }
        public string iOutstandingDate { get; set; }
        public string iCurrency { get; set; }
        public string iCreditClassification { get; set; }
        public string vDebtorNum { get; set; }
        public string vInterrelatedSourceName { get; set; }
    }
}
