//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFront
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACRA_osDays
    {
        public long osDaysId { get; set; }
        public Nullable<long> loanId { get; set; }
        public string osYear { get; set; }
        public string osMoth { get; set; }
        public string osValue { get; set; }
    }
}
