//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFront
{
    using System;
    
    public partial class ACRA_CreditUsePlacesGet_Result1
    {
        public Nullable<int> crUsPlId { get; set; }
        public string CreditUsePlace { get; set; }
    }
}
