//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASFront
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACRA_RequestesInfo
    {
        public long rsId { get; set; }
        public Nullable<long> resultId { get; set; }
        public string vNumber { get; set; }
        public string vBankName { get; set; }
        public string vDate { get; set; }
        public string vReason { get; set; }
        public string vSubReason { get; set; }
    }
}
